# Generated by Django 4.2.23 on 2025-07-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retractedpaper",
            name="article_type",
            field=models.CharField(
                blank=True, help_text="Type of article", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="retractedpaper",
            name="is_open_access",
            field=models.BooleanField(
                default=False, help_text="Whether the paper is open access"
            ),
        ),
        migrations.AddField(
            model_name="retractedpaper",
            name="original_paper_pubmed_id",
            field=models.CharField(
                blank=True,
                help_text="PubMed ID of original paper",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="retractedpaper",
            name="retraction_pubmed_id",
            field=models.CharField(
                blank=True,
                help_text="PubMed ID of retraction notice",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="retractedpaper",
            name="urls",
            field=models.TextField(blank=True, help_text="Additional URLs", null=True),
        ),
        migrations.AlterField(
            model_name="retractedpaper",
            name="country",
            field=models.CharField(
                blank=True, help_text="Country of origin", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="retractedpaper",
            name="institution",
            field=models.TextField(
                blank=True, help_text="Author institution(s)", null=True
            ),
        ),
    ]
