# Generated by Django 4.2.16 on 2025-08-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0008_democracyanalysisresults_democracydata_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="democracyanalysisresults",
            old_name="ci_lower",
            new_name="cri_lower",
        ),
        migrations.RenameField(
            model_name="democracyanalysisresults",
            old_name="ci_upper",
            new_name="cri_upper",
        ),
    ]
