runtime: python39

env_variables:
  DEBUG: "False"
  SECRET_KEY: "change-this-to-a-secure-secret-key-in-production"
  DJANGO_SETTINGS_MODULE: "citing_retracted.settings"
  # Add your database connection details here
  # DATABASE_URL: "postgresql://username:password@/db_name?host=/cloudsql/project:region:instance"

handlers:
# Static files
- url: /static
  static_dir: staticfiles/
  secure: always

# Send all other requests to Django
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Cloud SQL connections (uncomment and configure for production)
# beta_settings:
#   cloud_sql_instances: YOUR_PROJECT_ID:REGION:INSTANCE_NAME 