version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: citing_retracted
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/citing_retracted
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY=dev-secret-key-change-in-production

  celery:
    build: .
    command: celery -A citing_retracted worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/citing_retracted
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY=dev-secret-key-change-in-production

  celery-beat:
    build: .
    command: celery -A citing_retracted beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/citing_retracted
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY=dev-secret-key-change-in-production

volumes:
  postgres_data: 