version: '3.8'

services:
  predatory-detector:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/predatory_journals
      - MONGODB_URL=mongodb://mongo:27017/predatory_journals
      - REDIS_URL=redis://redis:6379/0
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - mongo
      - redis
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    networks:
      - predatory-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: predatory_journals
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - predatory-network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - predatory-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - predatory-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - predatory-detector
    networks:
      - predatory-network

volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  predatory-network:
    driver: bridge

